export * from "./CrearPolitica/CrearPolitica"
export * from "./Contact"
export * from "./Ejemplo"
export * from "./VerPoliticas/VerPoliticas.jsx"
export * from "./Login/Login.jsx"    
export * from "./Planificacion/Planificacion.jsx"   