export * from "./CrearPolitica/CrearPolitica"
export * from "./Planificacion/Planificacion.jsx"
export * from "./VerPoliticas/VerPoliticas.jsx"
export * from "./Login/Login.jsx"
export * from "./Inicio/Inicio.jsx"